spring:
  datasource:
    url: ${SUPABASE_DB_URL:jdbc:postgresql://localhost:5432/inkflow}
    username: ${SUPABASE_DB_USER:postgres}
    password: ${SUPABASE_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT:8080}

cors:
  allowed-origins: 
    - http://localhost:5173
    - https://*.vercel.app
    - https://inkflow-studios.vercel.app

jwt:
  secret: ${JWT_SECRET:inkflow-secret-key-2025-very-secure}
  expiration: 86400000